# Change these first
owner: 4hse # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Service
    url: https://service.4hse.com
  - name: Mobile
    url: https://mobile.4hse.com
  - name: Academy
    url: https://academy.4hse.com
  - name: WWW
    url: https://www.4hse.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: uptime.4hse.com
  baseUrl: /upptime
  logoUrl: https://www.4hse.com/wp-content/uploads/2023/09/4hse_logo_hg.png
  name: Up time 4hse
  introTitle: "4HSE Service status"
  introMessage: Welcome to our Service Status page. Here, you can find real-time updates about the availability and performance of our systems. We are committed to providing a reliable and transparent service. In the event of an issue, we will update this page with details about the incident, progress on the resolution, and an estimated time for recovery. You can also review past events to better understand our service's stability.
  navbar:
    - title: Status
      href: /upptime
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
