# Change these first
owner: 4hse # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Service
    url: https://service.4hse.com/site/login?$SKIP_WAF_FIREWALL
    icon: https://s3.eu-west-1.amazonaws.com/public.4hse.com/images/logo_4hse_icona300.png
  - name: Mobile
    url: https://mobile.4hse.com/?$SKIP_WAF_FIREWALL
    icon: https://s3.eu-west-1.amazonaws.com/public.4hse.com/images/logo_4hse_icona300.png
  - name: Docs
    url: https://docs.4hse.com/?$SKIP_WAF_FIREWALL
    icon: https://s3.eu-west-1.amazonaws.com/public.4hse.com/images/logo_4hse_icona300.png
  - name: WWW
    url: https://www.4hse.com
    icon: https://s3.eu-west-1.amazonaws.com/public.4hse.com/images/logo_4hse_icona300.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.4hse.com
  # baseUrl: /upptime
  faviconSvg: https://status.4hse.com/favicon.svg
  themeUrl: https://status.4hse.com/4hse.css
  logoUrl: https://status.4hse.com/logo.svg
  name: Status page
  introTitle: "4HSE Service status"
  introMessage: Welcome to our Service Status page. Here, you can find real-time updates about the availability and performance of our systems. We are committed to providing a reliable and transparent service. In the event of an issue, we will update this page with details about the incident, progress on the resolution, and an estimated time for recovery. You can also review past events to better understand our service's stability.
  navbar:
    - title: Status
      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
